# Change these first
owner: soxfor # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Media
    url: $SITE_1
    expectedStatusCodes:
      - 200
      - 302
  - name: Media Control
    url: $SITE_6
    expectedStatusCodes:
      - 401
  - name: Media Helper
    url: $SITE_8
    expectedStatusCodes:
      - 401
  - name: Cloud
    url: $SITE_2
    expectedStatusCodes:
      - 200
      - 302
  - name: Vault
    url: $SITE_3
    expectedStatusCodes:
      - 200
      - 302
  - name: SearchS
    url: $SITE_4
    expectedStatusCodes:
      - 401
  - name: SearchM
    url: $SITE_5
    expectedStatusCodes:
      - 401
  - name: Search Helper
    url: $SITE_7
    expectedStatusCodes:
      - 401
  - name: Provider
    check: "tcp-ping"
    url: $PROVIDER_1
    port: $PROVIDER_1_PORT
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upp.hpercld.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  theme: night
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/15 * * * *"

robotsText: "User-agent: * \n Disallow: /"

user-agent: soxfor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
